### ISSUE TITLE
Dbus config file / host extensions support?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/light-hotspot-software#28]
Relates to https://github.com/NebraLtd/helium-miner-software/issues/90

Need to discuss options with balena for light

**Comment by mpous** [comment]
Did you check the newest dbus block @shawaj https://github.com/balenablocks/dbus

Not sure about the context of the issue but maybe it can help!

**Comment by shawaj** [comment]
Trying it out here https://github.com/NebraLtd/hm-dbus

Haven't got it to work yet though.

Do you have any example projects using this @mpous ?

**Comment by shawaj** [comment]
Having some issues getting this to work @mpous but maybe I'm doing something stupid I'm not sure https://forums.balena.io/t/dbus-balena-block-configuration/348962

**Comment by shawaj** [comment]
Possibly fixed by ec67a9755eb4543ef2a14fbe1b8e0200d617996a
