### ISSUE TITLE
spike: Investigate and prototype changes for light miner

### ISSUE THREAD

**Issue by pritamghanghas** [NebraLtd/light-hotspot-software#45]
Investigate all activities that needs to be completed to get light miner at par with existing software and come up with prototypes and tickets for tackling them.

**Acceptance Criterion**
* gateway-rs integration with docker compose. a rough draft is already available.
* helium miner's dbus interface replacement work around.
* impact and mitigation of missing miner interfaces on hm-diag, hm-config and hm-pyhelper.

**Comment by pritamghanghas** [comment]
helium miner's dbus interface has following interfaces whose replacement will have to be investigated:
**AddGateway**
this trasaction is supposed to be generated by invoking gateway-rs from cmdline. Documented [here](https://github.com/helium/gateway-rs)
`./helium_gateway add --owner WALLET_ADDRESS --payer WALLET_ADDRESS`
it is implemented [here](https://github.com/helium/gateway-rs/blob/main/src/cmd/add.rs#L26)
It is possible that they will add it to the localhost:1648 grpc/jsonrpc interface but at this point in time it is not part of that. if helium doesn't we can. it would be a very small change. I have posted on gateway development discord channel to ask if they have any such plan.

**AssertLocation**
according to helium, this has to be client side code.

**P2PStatus**
Any mention of it can be removed as it will become useless after light miner migration.

**BlockAge
Height**
These two will work with the local [rpc interface](https://github.com/helium/proto/blob/master/src/service/local.proto ) implemented [here](https://github.com/helium/gateway-rs/blob/main/src/api/server.rs)

**Comment by pritamghanghas** [comment]
Final result: 
Add gateway and assert location are deemed to be client functions by helium. Everything that is needed to implement them on the client side is available in gateway local and remote rpc.

assert_location ref implementation can be found in [rust wallet](https://github.com/helium/helium-wallet-rs/blob/master/src/cmd/hotspots/assert.rs#L59)

add gateway transaction generation reference implementation can be found in [gateway-rs](https://github.com/helium/gateway-rs/blob/main/src/cmd/add.rs#L26)

For the time being we can modify gateway-rs to provide those convenience interfaces so that everything works till such time we implement it in the app.

we will replace implementation of these two api's in hmdiag.

**Comment by marvinmarnold** [comment]
@pritamghanghas can you give this task a difficulty estimate?

**Comment by pritamghanghas** [comment]
@marvinmarnold giving 2 because of rust where i had to refer documentation a lot.
