### ISSUE TITLE
DIY-RAK2287 variant, how to enable GPS?

### ISSUE THREAD

**Issue by rjwelling2** [NebraLtd/light-hotspot-software#7]
maybe not so much an issue but how to enable GPS on the DIY-RAK2287 variant.

I'm using a plain Raspi Pi4 4Gb with a RAK2287 with the GPS antenna connected.

BTW, I'm receiving traffic and familiar with LoRAN.

The message I picked up in to the logs;

### [GPS] ###
19.05.21 15:57:03 (+0200)  packet-forwarder  # GPS *FAKE* coordinates: latitude 0.00000, longitude 0.00000, altitude 0 m
19.05.21 15:57:03 (+0200)  packet-forwarder  ##### END #####

**Comment by shawaj** [comment]
@rjwelling2 helium doesn't really use the GPS so it is not required, but you can enable it if you want I suppose in the config.json templates

For example in here - https://github.com/NebraLtd/hm-pktfwd/blob/master/lora_templates_sx1301/AS923-3-global_conf.json

you would need to provide the path to the GPS module...for example:
https://github.com/Lora-net/packet_forwarder/blob/d0226eae6e7b6bbaec6117d0d2372bf17819c438/lora_pkt_fwd/cfg/global_conf.json.US902.gps#L102-L109

**Comment by shawaj** [comment]
https://github.com/Lora-net/packet_forwarder/blob/d0226eae6e7b6bbaec6117d0d2372bf17819c438/lora_pkt_fwd/cfg/global_conf.json.US902.gps#L102-L109
